baseURL = "https://shoesinbitcoin.com/"
languageCode = "en-us"
title = "Shoes in Bitcoin"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Valeriya Georgieva"
    description = "find your place in the Bitcoin industry"
    accent = "black"
    showBorder = true
    backgroundColor = "pink"
    font = "Raleway" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/jobs/"
    name = "Jobs"
    weight = 2

[[menu.main]]
    url = "/academy"
    name = "Academy"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://facebook.com/shoesinbitcoin/"
    name = "facebook"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/shoesinbitcoin/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/company/shoes-in-bitcoin/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
url = "https://www.instagram.com/shoes.inbitcoin/"
name = "instagram"
weight = 4

[[menu.icon]]
url = "https://www.youtube.com/channel/UC8k72dXIrN0CzRSZC9l8Uvw?view_as=subscriber"
name = "youtube"
weight = 5

[[menu.icon]]
url= "https://telegram.me/valgeorgieva"
name= "telegram"
weight = 6
